"""
Run once: python seed_catalog.py
Populates global_catalog collection with Hebrew supermarket items.
Safe to re-run — uses upsert on name.
"""
from pymongo import MongoClient, UpdateOne
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from config import Config

CATALOG = [
    # ירקות
    {"name": "עגבנייה",       "category": "ירקות"},
    {"name": "מלפפון",        "category": "ירקות"},
    {"name": "חסה",           "category": "ירקות"},
    {"name": "גזר",           "category": "ירקות"},
    {"name": "בצל",           "category": "ירקות"},
    {"name": "שום",           "category": "ירקות"},
    {"name": "תפוח אדמה",     "category": "ירקות"},
    {"name": "בטטה",          "category": "ירקות"},
    {"name": "כרוב",          "category": "ירקות"},
    {"name": "כרובית",        "category": "ירקות"},
    {"name": "ברוקולי",       "category": "ירקות"},
    {"name": "חציל",          "category": "ירקות"},
    {"name": "פלפל אדום",     "category": "ירקות"},
    {"name": "פלפל ירוק",     "category": "ירקות"},
    {"name": "פלפל צהוב",     "category": "ירקות"},
    {"name": "תרד",           "category": "ירקות"},
    {"name": "סלרי",          "category": "ירקות"},
    {"name": "זוקיני",        "category": "ירקות"},
    {"name": "דלעת",          "category": "ירקות"},
    {"name": "פטרייה",        "category": "ירקות"},
    {"name": "אבוקדו",        "category": "ירקות"},
    {"name": "עגבנייה שרי",   "category": "ירקות"},
    {"name": "כרישה",         "category": "ירקות"},
    {"name": "קולרבי",        "category": "ירקות"},
    {"name": "אספרגוס",       "category": "ירקות"},
    {"name": "פטרוזיליה",     "category": "ירקות"},
    {"name": "כוסברה",        "category": "ירקות"},
    {"name": "שמיר",          "category": "ירקות"},
    {"name": "בצל ירוק",      "category": "ירקות"},
    {"name": "צנון",          "category": "ירקות"},
    {"name": "בייבי סלרי",    "category": "ירקות"},
    {"name": "תירס",          "category": "ירקות"},
    {"name": "שעועית ירוקה",  "category": "ירקות"},
    {"name": "אפונה טרייה",   "category": "ירקות"},

    # פירות
    {"name": "תפוח",          "category": "פירות"},
    {"name": "אגס",           "category": "פירות"},
    {"name": "בננה",          "category": "פירות"},
    {"name": "תפוז",          "category": "פירות"},
    {"name": "מנדרינה",       "category": "פירות"},
    {"name": "לימון",         "category": "פירות"},
    {"name": "ענבים",         "category": "פירות"},
    {"name": "אבטיח",         "category": "פירות"},
    {"name": "מלון",          "category": "פירות"},
    {"name": "תות",           "category": "פירות"},
    {"name": "פטל",           "category": "פירות"},
    {"name": "אוכמניות",      "category": "פירות"},
    {"name": "קיווי",         "category": "פירות"},
    {"name": "מנגו",          "category": "פירות"},
    {"name": "אננס",          "category": "פירות"},
    {"name": "רימון",         "category": "פירות"},
    {"name": "תמרים",         "category": "פירות"},
    {"name": "שזיף",          "category": "פירות"},
    {"name": "אפרסק",         "category": "פירות"},
    {"name": "נקטרינה",       "category": "פירות"},
    {"name": "צימוקים",       "category": "פירות"},
    {"name": "משמש יבש",      "category": "פירות"},
    {"name": "שקדים",         "category": "פירות"},
    {"name": "אגוזי מלך",     "category": "פירות"},
    {"name": "קשיו",          "category": "פירות"},
    {"name": "פיסטוק",        "category": "פירות"},
    {"name": "בוטנים",        "category": "פירות"},
    {"name": "תאנים",         "category": "פירות"},
    {"name": "ליצ'י",         "category": "פירות"},

    # חלב וביצים
    {"name": "חלב",               "category": "מזון"},
    {"name": "חלב 3%",            "category": "מזון"},
    {"name": "חלב 1%",            "category": "מזון"},
    {"name": "חלב דל לקטוז",      "category": "מזון"},
    {"name": "שמנת",              "category": "מזון"},
    {"name": "שמנת חמוצה",        "category": "מזון"},
    {"name": "גבינה לבנה",        "category": "מזון"},
    {"name": "קוטג",              "category": "מזון"},
    {"name": "גבינה צהובה",       "category": "מזון"},
    {"name": "גבינה בולגרית",     "category": "מזון"},
    {"name": "מוצרלה",            "category": "מזון"},
    {"name": "פרמזן",             "category": "מזון"},
    {"name": "גבינת שמנת",        "category": "מזון"},
    {"name": "חמאה",              "category": "מזון"},
    {"name": "מרגרינה",           "category": "מזון"},
    {"name": "ביצים",             "category": "מזון"},
    {"name": "יוגורט",            "category": "מזון"},
    {"name": "יוגורט יווני",      "category": "מזון"},
    {"name": "לבן",               "category": "מזון"},
    {"name": "גבינת עיזים",       "category": "מזון"},
    {"name": "גבינת ריקוטה",      "category": "מזון"},
    {"name": "טחינה",             "category": "מזון"},
    {"name": "חומוס",             "category": "מזון"},

    # לחם ומאפים
    {"name": "לחם אחיד",      "category": "מזון"},
    {"name": "לחם מלא",       "category": "מזון"},
    {"name": "לחם שיפון",     "category": "מזון"},
    {"name": "לחמניות",       "category": "מזון"},
    {"name": "פיתות",         "category": "מזון"},
    {"name": "טורטייה",       "category": "מזון"},
    {"name": "בגט",           "category": "מזון"},
    {"name": "חלה",           "category": "מזון"},
    {"name": "לחם כוסמין",    "category": "מזון"},
    {"name": "לחם ללא גלוטן", "category": "מזון"},
    {"name": "קרואסון",       "category": "מזון"},
    {"name": "בייגלה",        "category": "מזון"},

    # קמח, אורז, פסטה
    {"name": "אורז",          "category": "מזון"},
    {"name": "אורז מלא",      "category": "מזון"},
    {"name": "פסטה",          "category": "מזון"},
    {"name": "ספגטי",         "category": "מזון"},
    {"name": "מקרוני",        "category": "מזון"},
    {"name": "קוסקוס",        "category": "מזון"},
    {"name": "פתיתים",        "category": "מזון"},
    {"name": "קמח",           "category": "מזון"},
    {"name": "קמח מלא",       "category": "מזון"},
    {"name": "קמח תירס",      "category": "מזון"},
    {"name": "שיבולת שועל",   "category": "מזון"},
    {"name": "גרנולה",        "category": "מזון"},
    {"name": "קורנפלקס",      "category": "מזון"},
    {"name": "קינואה",        "category": "מזון"},
    {"name": "כוסמת",         "category": "מזון"},
    {"name": "עדשים",         "category": "מזון"},
    {"name": "חומוס יבש",     "category": "מזון"},
    {"name": "שעועית יבשה",   "category": "מזון"},

    # שמנים, רטבים, תבלינים
    {"name": "שמן זית",           "category": "מזון"},
    {"name": "שמן קנולה",         "category": "מזון"},
    {"name": "חומץ",              "category": "מזון"},
    {"name": "רסק עגבניות",       "category": "מזון"},
    {"name": "שימורי עגבניות",    "category": "מזון"},
    {"name": "שימורי תירס",       "category": "מזון"},
    {"name": "שימורי אפונה",      "category": "מזון"},
    {"name": "שימורי טונה",       "category": "מזון"},
    {"name": "שימורי סרדינים",    "category": "מזון"},
    {"name": "מלח",               "category": "מזון"},
    {"name": "פלפל שחור",         "category": "מזון"},
    {"name": "פפריקה",            "category": "מזון"},
    {"name": "כמון",              "category": "מזון"},
    {"name": "קינמון",            "category": "מזון"},
    {"name": "כורכום",            "category": "מזון"},
    {"name": "אגוז מוסקט",        "category": "מזון"},
    {"name": "עלי דפנה",          "category": "מזון"},
    {"name": "זעתר",              "category": "מזון"},
    {"name": "סוכר",              "category": "מזון"},
    {"name": "סוכר חום",          "category": "מזון"},
    {"name": "דבש",               "category": "מזון"},
    {"name": "ריבה",              "category": "מזון"},
    {"name": "ממרח שוקולד",       "category": "מזון"},
    {"name": "חרדל",              "category": "מזון"},
    {"name": "מיונז",             "category": "מזון"},
    {"name": "קטשופ",             "category": "מזון"},

    # בשר ודגים
    {"name": "עוף שלם",       "category": "מזון"},
    {"name": "חזה עוף",       "category": "מזון"},
    {"name": "כרעיים",        "category": "מזון"},
    {"name": "כנפיים",        "category": "מזון"},
    {"name": "פרגית",         "category": "מזון"},
    {"name": "קציצות עוף",    "category": "מזון"},
    {"name": "שניצל עוף",     "category": "מזון"},
    {"name": "בשר טחון",      "category": "מזון"},
    {"name": "סטייק",         "category": "מזון"},
    {"name": "נקניקיות",      "category": "מזון"},
    {"name": "המבורגר",       "category": "מזון"},
    {"name": "כבש",           "category": "מזון"},
    {"name": "סלמון",         "category": "מזון"},
    {"name": "פילה דג",       "category": "מזון"},
    {"name": "דג מוסר ים",    "category": "מזון"},
    {"name": "גמבה",          "category": "מזון"},

    # שתייה
    {"name": "מים מינרלים",       "category": "מזון"},
    {"name": "מים מוגזים",        "category": "מזון"},
    {"name": "קולה",              "category": "מזון"},
    {"name": "ספרייט",            "category": "מזון"},
    {"name": "פנטה",              "category": "מזון"},
    {"name": "מיץ תפוזים",        "category": "מזון"},
    {"name": "מיץ תפוחים",        "category": "מזון"},
    {"name": "מיץ ענבים",         "category": "מזון"},
    {"name": "נקטר",              "category": "מזון"},
    {"name": "רד בול",            "category": "מזון"},
    {"name": "תה קר",             "category": "מזון"},
    {"name": "קפה קר",            "category": "מזון"},
    {"name": "בירה",              "category": "מזון"},
    {"name": "יין",               "category": "מזון"},
    {"name": "מיץ לימון",         "category": "מזון"},

    # קפה ותה
    {"name": "קפה טחון",      "category": "מזון"},
    {"name": "קפה נמס",       "category": "מזון"},
    {"name": "אספרסו",        "category": "מזון"},
    {"name": "קפסולות קפה",   "category": "מזון"},
    {"name": "תה שחור",       "category": "מזון"},
    {"name": "תה ירוק",       "category": "מזון"},
    {"name": "תה נענע",       "category": "מזון"},
    {"name": "תה קמומיל",     "category": "מזון"},
    {"name": "קקאו",          "category": "מזון"},
    {"name": "שוקו",          "category": "מזון"},

    # חטיפים וממתקים
    {"name": "ביסלי",         "category": "מזון"},
    {"name": "במבה",          "category": "מזון"},
    {"name": "פרינגלס",       "category": "מזון"},
    {"name": "דורכוס",        "category": "מזון"},
    {"name": "ציפס",          "category": "מזון"},
    {"name": "שוקולד",        "category": "מזון"},
    {"name": "קיטקט",         "category": "מזון"},
    {"name": "מילקה",         "category": "מזון"},
    {"name": "אורנג",         "category": "מזון"},
    {"name": "ביצת שוקולד",   "category": "מזון"},
    {"name": "גומיות",        "category": "מזון"},
    {"name": "סוכריות",       "category": "מזון"},
    {"name": "מסטיק",         "category": "מזון"},
    {"name": "חלבה",          "category": "מזון"},
    {"name": "גלידה",         "category": "מזון"},
    {"name": "ארטיק",         "category": "מזון"},
    {"name": "פופקורן",       "category": "מזון"},
    {"name": "עוגיות",        "category": "מזון"},
    {"name": "ביסקוויט",      "category": "מזון"},
    {"name": "וופל",          "category": "מזון"},
    {"name": "רוגלך",         "category": "מזון"},

    # ניקיון
    {"name": "אבקת כביסה",        "category": "ניקיון"},
    {"name": "נוזל כביסה",        "category": "ניקיון"},
    {"name": "מרכך כביסה",        "category": "ניקיון"},
    {"name": "נוזל כלים",         "category": "ניקיון"},
    {"name": "ספוגיות",           "category": "ניקיון"},
    {"name": "מגבות נייר",        "category": "ניקיון"},
    {"name": "נייר טואלט",        "category": "ניקיון"},
    {"name": "שקיות אשפה",        "category": "ניקיון"},
    {"name": "נוזל רצפה",         "category": "ניקיון"},
    {"name": "קרם שירותים",       "category": "ניקיון"},
    {"name": "מנקה אמבטיה",       "category": "ניקיון"},
    {"name": "מסיר לכלוך",        "category": "ניקיון"},
    {"name": "נייר כסף",          "category": "ניקיון"},
    {"name": "ניילון נצמד",       "category": "ניקיון"},
    {"name": "שקיות ניילון",      "category": "ניקיון"},
    {"name": "מגב",               "category": "ניקיון"},
    {"name": "מטאטא",             "category": "ניקיון"},
    {"name": "מוחק כלים",         "category": "ניקיון"},
    {"name": "כפפות גומי",        "category": "ניקיון"},
    {"name": "חומר ניקוי כללי",   "category": "ניקיון"},
    {"name": "טאבלטים למדיח",     "category": "ניקיון"},
    {"name": "מלח למדיח",         "category": "ניקיון"},

    # פארם וטיפוח
    {"name": "שמפו",              "category": "פארם"},
    {"name": "מרכך שיער",         "category": "פארם"},
    {"name": "סבון ידיים",        "category": "פארם"},
    {"name": "סבון גוף",          "category": "פארם"},
    {"name": "קרם גוף",           "category": "פארם"},
    {"name": "קרם פנים",          "category": "פארם"},
    {"name": "קרם שמש",           "category": "פארם"},
    {"name": "דאודורנט",          "category": "פארם"},
    {"name": "משחת שיניים",       "category": "פארם"},
    {"name": "מברשת שיניים",      "category": "פארם"},
    {"name": "חוט דנטלי",         "category": "פארם"},
    {"name": "שפתון",             "category": "פארם"},
    {"name": "קצף גילוח",         "category": "פארם"},
    {"name": "סכיני גילוח",       "category": "פארם"},
    {"name": "כותנה",             "category": "פארם"},
    {"name": "אספירין",           "category": "פארם"},
    {"name": "פרמול",             "category": "פארם"},
    {"name": "אקמול",             "category": "פארם"},
    {"name": "וזלין",             "category": "פארם"},
    {"name": "פלסטרים",           "category": "פארם"},
    {"name": "ויטמין C",          "category": "פארם"},
    {"name": "ויטמין D",          "category": "פארם"},
    {"name": "מגנזיום",           "category": "פארם"},
    {"name": "אבץ",               "category": "פארם"},

    # תינוקות
    {"name": "חיתולים",       "category": "תינוקות"},
    {"name": "מגבונים לחים",  "category": "תינוקות"},
    {"name": "שמפו לתינוק",   "category": "תינוקות"},
    {"name": "קרם חיתול",     "category": "תינוקות"},
    {"name": "פורמולה",       "category": "תינוקות"},
    {"name": "דייסת תינוקות", "category": "תינוקות"},
    {"name": "שנוצר",         "category": "תינוקות"},
    {"name": "בקבוק לתינוק",  "category": "תינוקות"},
    {"name": "מזון תינוקות",  "category": "תינוקות"},
]

def seed():
    uri = Config.MONGO_URI
    db_name = uri.rsplit('/', 1)[-1].split('?')[0] or 'family_hub'
    client = MongoClient(uri)
    db = client[db_name]

    ops = [
        UpdateOne({'name': item['name']}, {'$set': item}, upsert=True)
        for item in CATALOG
    ]
    result = db.global_catalog.bulk_write(ops)
    db.global_catalog.create_index('name')

    print(f"OK Seeded {len(CATALOG)} items "
          f"({result.upserted_count} new, {result.modified_count} updated)")
    client.close()

if __name__ == '__main__':
    seed()
